// Icon barrel — re-exports from lucide-react
import { Star } from 'lucide-react'

export {
  Search as IconSearch,
  Plus as IconPlus,
  Settings as IconSettings,
  Star as IconStar,
  ChevronRight as IconChevronRight,
  ChevronDown as IconChevronDown,
  ChevronUp as IconChevronUp,
  SendHorizonal as IconSend,
  Trash2 as IconTrash,
  Copy as IconCopy,
  Cpu as IconCpu,
  X as IconX,
  X as IconWinClose,
  Wrench as IconWrench,
  Minus as IconWinMin,
  Square as IconWinMax,
  AlertCircle as IconAlertCircle,
  Check as IconCheck,
  RefreshCw as IconRefresh,
  Zap as IconZap,
  Menu as IconMenu,
  Pencil as IconEdit,
  Pin as IconPin,
  PinOff as IconPinOff,
  Command as IconCommand,
  PanelLeftClose as IconPanelLeftClose,
  PanelLeft as IconPanelLeft,
  Shield as IconShield,
  Brain as IconBrain,
  File as IconFile,
  Activity as IconActivity,
  Loader as IconLoader,
  XCircle as IconXCircle,
  Wifi as IconWifi,
  WifiOff as IconWifiOff,
  ExternalLink as IconExternalLink,
  Paperclip as IconPaperclip,
  Image as IconImage,
  Eye as IconEye,
  FolderOpen as IconFolder,
  Package as IconPackage,
  FileText as IconFileText,
  Lightbulb as IconLightbulb,
  RotateCcw as IconRotateCcw,
  BookOpen as IconBookOpen,
  Sparkles as IconSparkles,
  Terminal as IconTerminal,
  // Additional icons for settings tabs
  Bot as IconBot,
  Box as IconBox,
  Network as IconNetwork,
  BarChart3 as IconBarChart,
  MessageSquare as IconMessageSquare,
  ListTodo as IconListTodo,
  PawPrint as IconPawPrint,
  Info as IconInfo,
  Puzzle as IconPuzzle,
  Globe as IconGlobe,
  Server as IconServer,
  Store as IconStore,
  CalendarClock as IconCalendarClock,
  Clock as IconClock,
  History as IconHistory,
  Pause as IconPause,
  Play as IconPlay,
  StopCircle as IconStopCircle,
  ArrowLeft as IconArrowLeft,
  Save as IconSave,
  MoreHorizontal as IconMoreHorizontal,
  FilePlus as IconFilePlus,
  FolderOpen as IconFolderOpen,
  Folder as IconFolderClosed,
  Bug as IconBug,
  Download as IconDownload,
  // Write mode inline agent toolbar icons
  Bold as IconBold,
  Italic as IconItalic,
  Strikethrough as IconStrikethrough,
  Code2 as IconCode2,
  Quote as IconQuote,
  List as IconList,
  ListOrdered as IconListOrdered,
  Heading1 as IconHeading1,
  Heading2 as IconHeading2,
  Heading3 as IconHeading3,
  Type as IconType,
  Pilcrow as IconPilcrow,
  // Write mode persona icons
  Workflow as IconWorkflow,
  PenLine as IconPenLine,
  ScanSearch as IconScanSearch,
  ClipboardCheck as IconClipboardCheck,
  QrCode as IconQrCode,
  GitBranch as IconGitBranch,
  Users as IconUsers,
} from 'lucide-react'

export function IconStarFilled({ size = 16, className = '' }: { size?: number; className?: string }) {
  return <Star size={size} className={className} fill="currentColor" />
}
