// Auto-generated by specta from loom-types. Do not edit manually.
// Placeholder — will be populated when specta export is wired.

export type JsonRpcRequest = {
  jsonrpc: string
  method: string
  params?: unknown
  id: number
}

export type JsonRpcResponse = {
  jsonrpc: string
  result?: unknown
  error?: { code: number; message: string; data?: unknown }
  id: number
}

// === Model Config (mirrors backend ModelConfig) ===

export type ModelBackend = 'LmStudio' | 'Anthropic' | 'OpenAI' | 'DeepSeek' | 'Ollama' | 'Custom'

export interface ModelConfig {
  name: string
  model?: string
  model_type: 'Router' | 'Summarizer' | 'Reasoning'
  backend: ModelBackend
  backend_label?: string
  base_url?: string
  api_key_env?: string
  api_format?: string
  context_size: number
  max_output_tokens?: number
  is_active?: boolean
  capabilities?: ModelCapabilities
}

export interface ModelCapabilities {
  vision?: boolean
  reasoning?: boolean
  function_calling?: boolean
}

export interface ModelListItem {
  name: string
  model?: string
  backend: string
  backend_label?: string
  base_url?: string
  is_active: boolean
  context_size?: number
  capabilities?: ModelCapabilities
}
