// Auto-generated by specta from loom-types. Do not edit manually.
// Placeholder — will be populated when specta export is wired.

export type JsonRpcRequest = {
  jsonrpc: string
  method: string
  params?: unknown
  id: number
}

export type JsonRpcResponse = {
  jsonrpc: string
  result?: unknown
  error?: { code: number; message: string; data?: unknown }
  id: number
}
