// Auto-generated by specta from loom-types. Do not edit manually.
// Placeholder — will be populated when specta export is wired.

export type JsonRpcRequest = {
  jsonrpc: string
  method: string
  params?: unknown
  id: number
}

export type JsonRpcResponse = {
  jsonrpc: string
  result?: unknown
  error?: { code: number; message: string; data?: unknown }
  id: number
}

// === Model Config (mirrors backend ModelConfig) ===

export type ModelBackend = 'LmStudio' | 'Anthropic' | 'OpenAI' | 'DeepSeek' | 'Ollama' | 'Custom'

export interface ModelConfig {
  name: string
  model?: string
  model_type: 'Router' | 'Summarizer' | 'Reasoning'
  backend: ModelBackend
  backend_label?: string
  base_url?: string
  api_key_env?: string
  api_format?: string
  context_size: number
  max_output_tokens?: number
  is_active?: boolean
  capabilities?: ModelCapabilities
}

export interface ModelCapabilities {
  vision?: boolean
  reasoning?: boolean
  function_calling?: boolean
}

// === Knowledge Graph ===

export interface KgNode {
  node_id: number
  name: string
  entity_type: string
  description: string
  confidence: number
}

export interface KgEdge {
  source: string
  target: string
  relation_type: string
  fact: string
  confidence: number
}

export interface KgGraph {
  nodes: KgNode[]
  edges: KgEdge[]
}

export interface KgStats {
  node_count: number
  edge_count: number
}

export interface ModelListItem {
  name: string
  model?: string
  backend: string
  backend_label?: string
  base_url?: string
  api_key_env?: string
  is_active: boolean
  context_size?: number
  capabilities?: ModelCapabilities
  input_price?: number
  output_price?: number
  cache_read_price?: number
  cache_write_price?: number
}
